### ISSUE TITLE
Add support for the Kafka protocol

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#1006]
### Structure
Kafka protocol has multiple messages per publish call

### Performance concerns
How do we do allocations when parsing the Kafka message. 
Do we do what we do with C* and guess if we need to parse it or not... or do we do something smarter and allocate all at once (bump allocator?), or just point into the existing bytes (index into the byte array).

Protocol should be pretty simple in terms of needing to parse. 

How does parsing / zero copy bytes from the network all interact with call into IO accelerator code

**Comment by benbromhead** [comment]
Versions!!!! (support every version of the protocol)

**Comment by rukai** [comment]
Our kafka protocol support needs to be fast for our intended use case and I've been researching the tools that rust gives us to make this happen.

I originally thought we would be able to do a quick hack of  "just directly manipulate the bytes" for our fast message rewriting needs but it turns out that publish messages have 3-4 layers of nested list types so that would be quite a challenging hack.

Usually when writing zero-copy deserialization you dont need to support the user modifying the data structure and then serializing it again.
That ideal scenario means that all the existing options i've found fall just short of what we need, but I dont think its actually impossible to get what we want.

## serde approach

There is a bunch of resources for kafka zerocopy via serde:
* serde can already use `std::borrow::Cow` to zerocopy deserialize a string.
* [zerovec](https://docs.rs/zerovec/latest/zerovec/) provides `Vec` and `HashMap` equivalents that deserialize from serde and refer to the original buffer to get their values, unless they are modified in which case they take ownership of their data and heap allocate. So they are effectively `std::borrow::Cow` for `Vec`.
* https://github.com/DataDog/kafka-serde allows us to define kafka messages that can be serde serialized/deserialized, however it does not provide the message definitions itself.
* This can then be combined with [yoke](https://docs.rs/yoke/latest/yoke/index.html) to allow the deserialized message to be passed around without lifetimes getting in the way.

If we were to try to combine these into a solution we would hit these issues:
* Yoke gets in the way of us modifying the message after its been created - https://github.com/unicode-org/icu4x/issues/3134
* kafka-serde does not provide message definitions so we will have to do that ourselves, hopefully every kafka message is expressible in serde.

## custom approach

If the serde approach doesnt work out, either due to serdes overhead or an unexpected hidden obstacle, we can implement what the serde approach would be doing directly for kafka, i.e. come up with our own zerocopy kafka protocol implementation, including our own kafka specific alternative to zerovec

## way forward

These problems dont seem insurmountable but it needs a lot of research and a lot of implementation.
To get the project going I am going to proceed with adding kafka protocol support via https://github.com/tychedelia/kafka-protocol-rs
It allocates and copies all of its data but we can use it to demonstrate the feasibility of the IO acceleration project and it will also give us a baseline upon which we can profile and compare against any zerocopy approach we come up with in the future.

**Comment by rukai** [comment]
I'm going to close this as our kafka protocol support is fairly complete, https://github.com/shotover/shotover-proxy/issues/1214 will continue to track KafkaSinkCluster improvements
