### ISSUE TITLE
Change encrypted values to being stored as a binary blob

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#1032]
I think we might be storing encrypted values as base64 encoded text rather than just a binary blob. Let's use the right data types.

**Comment by conorbros** [comment]
As far as I can tell we only use base64 for the keys, the encrypted values are serialised using `bincode`

**Comment by rukai** [comment]
You might have been mixed up by, as conor said, our use of base64 for storing the keys.

Alternatively you might have seen:
https://github.com/shotover/shotover-proxy/blob/5acb99307a7295fe0f2fb21ee20412971404f372/shotover/src/transforms/protect/crypto.rs#L41-L43
and gotten concerned due to the encrypted payload being stored as a hex encoded string.
Unfortunately that is just how the cassandra protocol specifies binary values for inserting.
When we read it out again from cassandra, it comes back as a binary blob.

Although thinking about it, we might be able to rewrite the query to store the binary value as a query parameter instead of inline in the query string.
Might be worth an experiment.

**Comment by rukai** [comment]
Since we are not actively working on the protect transform I'm closing this in favor of a single protect transform issue https://github.com/shotover/shotover-proxy/issues/676
