### ISSUE TITLE
WASM plugins

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#1037]

**Comment by rukai** [comment]
wasm plugins were explored but we decided to instead pursue a "shotover as a library" custom transforms approach instead.
Our conclusion was that there was no ergonomic and performant interface that we could provide for wasm plugins.
In particular needing to expose our rusty message AST's to the plugin seemed impossible with current wasm technologies.
We left wasm plugins as an idea we might come back to you.

Over a year later I dont think there is any desire for wasm plugins anymore, in part due to shifting priorities of the project but also due to our current custom transforms approach covering any remaining needs that we might have for wasm.
