### ISSUE TITLE
Reenable test_protect_kms_transform

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#316]
We had to disable this in https://github.com/shotover/shotover-proxy/pull/315 due to making the repo public preventing the use of github secrets.

Maybe we can mock out the AWS API like https://github.com/spulec/moto
Or maybe theres a way to safely distribute the key or a lower access key.

**Comment by Claude-at-Instaclustr** [comment]
It looks like we can use the docker version of [moto](https://hub.docker.com/r/motoserver/moto) to create a mock AWS service and call that from the tests.

**Comment by Claude-at-Instaclustr** [comment]
I have a [branch](https://github.com/Claude-at-Instaclustr/shotover-proxy/tree/Issue_316) that contains the changed necessary to talk to a mocked AWS.  However, I have not been able to get dockerized moto to create a key so that it can be retrieved by the test.  Once that is done, adding the scripts to start/stop the docker and set it up should be fairly simple. <-- Famous last words those.
