### ISSUE TITLE
DebugReturner changes

### ISSUE THREAD

**Issue by conorbros** [shotover/shotover-proxy#370]
- [ ] document our now public API for DebugReturner
- [ ] Remove the "response" field by either:
                 - writing the type as struct DebugReturner (Response)
                 - adding a serde attribute to merge with the parent.

**Comment by rukai** [comment]
These should be a prereq for making DebugReturner public.

We want to ensure the codebase is always in a state such that we can make a release at any time.

To achieve that we should only make transforms public once they are ready.

I realize I am being a bit pedantic when this is "just" a debug transform and this is early days for shotover, but I think we should build these kinds of habits so that we get practice working in this manner.

**Comment by conorbros** [comment]
Seems DebugRandomDelay doesn't have docs either even though it's public. I'll open a PR with docs for both
