### ISSUE TITLE
Tee transform breaks auth isolation because BufferedChains are shared

### ISSUE THREAD

**Issue by XA21X** [shotover/shotover-proxy#385]
## Describe the bug
This is another auth isolation bug that is very similar to #204. Authentication support in RedisSinkCluster assumes that each instance of itself is dedicated per client connection to Shotover. Transforms like Tee (and the since-removed PoolConnections) stores state in shared references (Arc) in a way that violates this assumption.

## To Reproduce
1. Add auth support to the `redis-cluster-dr` example.
2. Connect to primary cluster using redis-cli without authentication.
3. Connect to primary cluster using redis-cli with authentication.
4. Connect to secondary cluster using redis-cli with authentication.
5. Attempt to write something using (2), which should fail with a NOAUTH.
6. Check that the write did not go through using (4)... and this is is the problem. The write went through.

The successful authentication from (3) also authenticates the shared DR chain, which is also used by (2).

## Expected behaviour
- Unauthenticated connections must be prevented from writing to the secondary (DR) cluster.
- Authenticated contexts must be kept isolated between connections.
- BufferedChains possibly shouldn't be shared by default?

## Systems and Version:
 - Shotover Version 0.1.0

**Comment by benbromhead** [comment]
Some thoughts:
So this is likely to be a "big" fix issue as it will require some restructuring of how we share data amongst different connections.

Previously we've discussed things like colored connections or auth contexts etc. 

I think right now the simplest could be attaching context to each Wrapper (or individual message) and one of these could be an auth context. Then on both Tee and Connection pooling we maintain a map of contexts to senders (this should be ok with just a `&` ref ?)

Contexts would need to be modifiable by transforms and then an authentication aware transform (or maybe at the protocol/server) we would inject the context into the Wrapper / message. The downside with a transform based approach to auth context tagging is it requires a user to add it to the chain, rather than just having it on by default. 

It probably needs to live on the source side of things (though a lot of the logic is done at the tcp listener). One idea I had was the concept of default transforms, or source generated transforms. Where the cassandra source will actually prepend / or modify the transform chains with it's own set of transforms it needs to do Cassandra things.

That way it keeps the Transform model a little more pure, takes a cognitive load off the user in having to build the right chain just to get a certain protocol working and keeps protocol specific code out of tcp_listener?

**Comment by benbromhead** [comment]
A much simpler fix however for this issue would be to override the clone implementation and clone `chain_to_clone` and then turn that into the buffered chain for the new one as it was supposed to originally I beleive (which is why it has chain_to_clone).

**Comment by rukai** [comment]
You are talking about the manually implementing `Clone` on `Tee` right?
I tried that and it doesnt work.
I think its because the messages get held around in the coallesce, all the in progress messages get thrown away everytime a new connection is made.

**Comment by benbromhead** [comment]
That behavior doesn’t sound quite right?

Also what do you
Mean by progress messages? Like the responses?

**Comment by benbromhead** [comment]
Anything in progress in coalesce should still be on a valid chain attached to a valid connection. When your testing are you generating enough messages on both the old connection and the new one to cause coalesce to flush?

We can just take it out to simplify testing this issues

**Comment by rukai** [comment]
Taking it out sounds like a bad idea, as that would just be ignoring what appears to be a real issue. I'm sending enough messages to trigger the the coalesce to flush.

running `cargo test test_cluster_dr_redis` on https://github.com/rukai/shotover-proxy/tree/fix_redis_auth should demonstrate the problem.

**Comment by rukai** [comment]
Hmmm strange that its not causing any regressions in the other tee-coalesce integration tests, maybe I messed something up

**Comment by rukai** [comment]
Oh right, it makes sense that no other integration tests hit this because they all use just one connection.

In conclusion: The reason we cant use this approach is because it would mean a connection that closes before the coalesce flushes would result in lost messages.

**Comment by rukai** [comment]
oh, maybe coalesce needs functionality to flush it is closed?
As is there would be lost messages when shotover shuts down.

**Comment by benbromhead** [comment]
So a few thoughts:
- Coalesce needs to flush on close (mind you we don't guarentee delivery due to the use of Tee, so not a big drama anyway). Coalesce also has a flush based on a time window (but interestingly needs another message to come in to trigger it).
- Coalesce probably needs its own clone implementation so we don't keep copying the buffer in general (we are not getting duplicates at the moment because we are cloneing the `chain_to_clone` which always sits empty.

Taking out the coalesce in this case was actually more just about seperating out the issues (one is the shared chain) vs what's going on with coalesce which is probably a seperate bug (in my mind).

**Comment by rukai** [comment]
Right, that sounds good.
I'll work on coalesce flush on close first, otherwise fixing the auth bug would result in what I think is a worse regression.
