### ISSUE TITLE
RedisSinkCluster self.masters sometimes contains replicas

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#632]
I have observed a random test failure https://github.com/shotover/shotover-proxy/runs/6290958118?check_suite_focus=true occur because a RoutingInfo::Slot command was routed to a replica and the command "CLUSTER REPLICAS" must be run against a master.
The only way for this to have occurred is for self.slots.masters to have contained a replica.

![image](https://user-images.githubusercontent.com/5120858/166857550-0cb96ff8-4913-46cb-8083-ae9a5d982fae.png)

**Comment by rukai** [comment]
I took a look at this because it sounded dangerous but I am giving up for now.
just very confused how this could happen at all.

The self.slots.master generation seems sound.

The only remaining possibilities I can think of is either:
* a master node failed and was swapped with a replica node - this cant be it because I'm sure we would hit other errors first in the case of such a failure
* a redis cluster from a previous test is still partially running and the networking is sometimes hitting the old cluster :shrug: - seems to farfetched

**Comment by benbromhead** [comment]
This could likely occur due to a split brain in the cluster, or we havn't caught things up. I have seen this error during a failover in the redis cluster while running test suites. 

I think for most queries, we generally expect either a mov or an ask as the response when this occurs. I guess `SLOTS` errors out differently. Without digging into the flow of CLUSTER REPLICAS and what it does, my gut would be to try rebuilding our slot list when we get this and then giving up if it still happens (that indicates the cluster would be in a weird state).

**Comment by rukai** [comment]
While investigating the intermittent failure, I discovered the true cause which I raised a PR for here https://github.com/shotover/shotover-proxy/pull/1792 , but its worth noting that the reasoning in my original comment is flawed and doesnt really make sense.
In that test case we arent running `CLUSTER REPLICAS` but `CLUSTER REPLICAS $ID` which has different routing requirements.
