### ISSUE TITLE
Pushed messages

### ISSUE THREAD

**Issue by conorbros** [shotover/shotover-proxy#646]
# Pushed messages design

I'm opening this issue to discuss the design of implementing support for [PubSub messages](https://redis.io/docs/manual/pubsub/) in Redis and [events](https://github.com/apache/cassandra/blob/7b927eaad3c42657951df688673598b2594514d4/doc/native_protocol_v4.spec#L754) in Cassandra.

## Sink changes

Introduce a channel producer to each sink that we send the pushed messages read off the socket into. Any processing that the sink needs to do to the message can be done here (keep some sort of state, etc). We would give the sink this producer channel when the chain is loaded, similar to the already existing shutdown channel.

## Chain changes

Introduce a new method for processing a message in reverse on the chain, we would also need to add method to the transform trait that processes the messages in reverse, for most transforms this can be a default implementation (straight pass through).

One thing we will to discuss is how we will use the chain as the source already has a mutable reference to it, my current thinking is just to clone it and have a separate chain for the pushed messages. This does mean we can't share any state with the other chain on the connection but at least for the time being we won't need it.

## Source changes

Spawn a tokio task waiting for messages on the pushed messages channel.

Once we receive these messages we call the reverse processing method on our chain and then send the result to the client.

![Blank diagram (3)](https://user-images.githubusercontent.com/39339036/168744553-3ddef0a6-2953-44cf-8099-8a3d656d121d.png)

**Comment by benbromhead** [comment]
A few questions from me:

- How do we know what messages are pushed? For example the C* protocol has an `EVENT` message type which makes this simple. Whereas in Redis a subscription changes the semantics of the connection and uses an array-reply (https://redis.io/docs/manual/pubsub/) which shares some commonality with other response types. In the case of redis we should still be able to discriminate whether the frame is related to a push event? Will it be up to the `sink` to implement what frames are events/messages vs a query response?
- Could split borrows work with the Transform chain (if we rather than borrowing a list of mut refs to the transform chain, we create a new `event` struct using the same `TransformConfig` instance)? E.g. `get_transform()` will now return a `Transform` and a `EventTransform` or something... and they can both live in the same transform chain... Then if a transform author ever needs to share state between events and queries, they can construct an `arc<mutex<?>>` in the config method and use that to share between the two.

**Comment by conorbros** [comment]
>Will it be up to the sink to implement what frames are events/messages vs a query response?

Yes, for Cassandra I put the logic that decides whether a message should be pushed or is a normal request/response in the task that processes the read side of the socket.

>Could split borrows work with the Transform chain 

I've managed to get it working without cloning the transform chain. See #662

**Comment by conorbros** [comment]
Closing as https://github.com/shotover/shotover-proxy/pull/662 was merged.
